# Generated by Django 4.1.7 on 2023-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=200, unique=True, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
