# Generated by Django 4.2.3 on 2023-07-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزئیات سبد خرید', 'verbose_name_plural': 'لیست جزيیات سبد خرید'},
        ),
    ]
