# Generated by Django 4.1.7 on 2023-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_userprofile_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل یوزر', 'verbose_name_plural': 'پروفایل های کاربر'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(upload_to='images', verbose_name='عکس کاربر'),
        ),
    ]
