# Generated by Django 4.1.7 on 2023-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_options_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل های کاربر'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(unique=True, upload_to='images', verbose_name='عکس کاربر'),
        ),
    ]
