# Generated by Django 4.1.7 on 2023-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_alter_userprofile_options_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(upload_to='images', verbose_name='عکس کاربر'),
        ),
    ]
