# Generated by Django 4.1.7 on 2023-06-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظرات های مقاله', 'verbose_name_plural': 'نظرات های مقالات'},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_set', to='article_module.articlecomment', verbose_name='والد'),
        ),
    ]
