# Generated by Django 4.1.7 on 2023-06-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='', verbose_name='تصویر اواتار'),
        ),
    ]
